In [1]:
#Numpy and its functionalities
import numpy as np

In [2]:
#numpy.arange(stop)
print(np.arange(5))
#numpy.arange(start,stop)
print(np.arange(1,10))
#numpy.arange(start,stop,step)
print(np.arange(1,10,2))

[0 1 2 3 4]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [3]:
#Array using lists
lst=[[2,4,3],[1,4,5]]
x=np.array(lst)
print(x)

[[2 4 3]
 [1 4 5]]


In [4]:
#np.full
full=np.full((2,2),10)
print(full)

[[10 10]
 [10 10]]


In [5]:
#np.linspace

print(np.linspace(0, 10, 5))
print(np.linspace(0, 10, 5))
print(np.linspace(0, 10,))

[ 0.   2.5  5.   7.5 10. ]
[ 0.   2.5  5.   7.5 10. ]
[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [6]:
#matrix full of 1s
one=np.ones((2,2))
print(one)

[[1. 1.]
 [1. 1.]]


In [7]:
#Matrix full of 0s
zero=np.zeros((2,2))
print(zero)

[[0. 0.]
 [0. 0.]]


In [8]:
#shape is the row and column of the matrix
myarray1=np.array([1,2,3,4])
myarray2=np.array([[1,2,3,4],[6,7,8,9]])
print("ARRAY 1:", myarray1)
print("shape of array1:", myarray1.shape)
print("ARRAY 2:", myarray2)
print("shape of array2:", myarray2.shape)

ARRAY 1: [1 2 3 4]
shape of array1: (4,)
ARRAY 2: [[1 2 3 4]
 [6 7 8 9]]
shape of array2: (2, 4)


In [9]:
#changing array elemets using Indexing
myarray=np.array([1,2,3,4,5,6,7,8])
print("original array:", myarray)

myarray[0]=20
print("updated array:", myarray)

original array: [1 2 3 4 5 6 7 8]
updated array: [20  2  3  4  5  6  7  8]


In [10]:
#function creates an array with random floats between the intervals.
#you can also specify the size of your array. 

random=np.random.random((3,3))
print(random)

[[0.75446582 0.73207011 0.64386979]
 [0.6413358  0.58041004 0.98088213]
 [0.98940587 0.58013075 0.0894626 ]]


In [11]:
#function creates an array with random integers between a specified range.
#you can also specify the size of your array

integer=np.random.randint(0,10, (3,3))
print(integer)

[[6 5 3]
 [3 7 6]
 [1 5 0]]


In [12]:
#since identity matrix is a square matrix, we just need 1 number to determine rows and columns.

I_1=np.eye(2)
print(I_1,"\n")

I_2=np.eye(5)
print(I_2,"\n")

[[1. 0.]
 [0. 1.]] 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

