In [1]:
# More Array Functions
# Using NumPy
import numpy as np

In [2]:
#Array Slicing

A=np.array([[1,2,3],[4,5,6],[7,8,9]])

#Syntax array[start_row:end_row-1,start_col:end_col-1]
x=A[0:1,1:2]
print(x)

[[2]]


In [3]:
#Array Reverse

A=np.array([[1,2,3],[4,5,6],[7,8,9]])
myarray=A[::-1]

print(A,"\n")
print(myarray,"\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[7 8 9]
 [4 5 6]
 [1 2 3]] 



In [4]:
#Array Reshape

A=np.array([[1,2,3],[4,5,6],[7,8,9]])

B=A.reshape(1,9)
print(B,"\n")

C=A.reshape(9,1)
print(C,"\n")

[[1 2 3 4 5 6 7 8 9]] 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]] 

