In [1]:
import numpy as np

In [ ]:
#Appending in list
x=[1,2,3,4]
print(x)

y=np.append(x,[11,12])
print(y)

In [ ]:
#Appending in column
x=np.array([[1,2],[3,4]])
print(x)

y=np.append(x,[[11,12]],axis=0)
print(y)

In [ ]:
#Appending in row
x=np.array([[1,2],[3,4]])
print(x)

y=np.append(x,[[11],[12]],axis=1)
print(y)

In [ ]:
#Inserting in row
x=np.array([[1,2],[3,4]])
print(x)

y=np.insert(x,1,[[11,12]],axis=0)
print(y)

In [ ]:
#Inserting in colunn
x=np.array([[1,2],[3,4]])
print(x)

y=np.insert(x,1,[[11,12]],axis=1)
print(y)

In [ ]:
#deleting row
x=np.array([[1,2],[3,4]])
print(x)

y=np.delete(x,1,axis=1)
print(y)

In [ ]:
#deleting column
x=np.array([[1,2],[3,4]])
print(x)

y=np.delete(x,1,axis=0)
print(y)

In [3]:
#sorting by row
x=np.array([[8,5,7],[88,4,89]])
print(x)

y=np.sort(x,axis=0)
print(y)

[[ 8  5  7]
 [88  4 89]]
[[ 8  4  7]
 [88  5 89]]


In [5]:
#sorting by column
x=np.array([[8,5,7],[88,4,89]])
print(x)

y=np.sort(x,axis=1)
print(y)

[[ 8  5  7]
 [88  4 89]]
[[ 5  7  8]
 [ 4 88 89]]


In [ ]:
#Stacking horizontally

x=np.arange(10).reshape(5,-1)
y=np.arange(10,20).reshape(5,-1)

z=np.concatenate( [x,y], axis=1)
print(z)

In [ ]:
#Stacking vertically

x=np.arange(10).reshape(5,-1)
y=np.arange(10,20).reshape(5,-1)

z=np.concatenate( [x,y], axis=0)
print(z)

In [ ]:
y = np.array([[2,7,3],[8,3,5],[4,0,9]])


# Find the mean of all elements
print("The mean of all elements:\n", y.mean(), "\n")


In [ ]:
y = np.array([[2,7,3],[8,3,5],[4,0,9]])

# Find the mean of elements in the rows
print("The mean of elements in rows:\n", y.mean(axis=1), "\n")


In [ ]:
y = np.array([[2,7,3],[8,3,5],[4,0,9]])

# Find the mean of elements in the columns
print("The mean of elements in columns:\n", y.mean(axis=0), "\n")


In [ ]:

y = np.array([[2,7,3],[8,3,5],[4,0,9]])
print("The original array:\n", y, "\n")
# Find the sum of all elements
print("The sum of all elements:\n", np.sum(y), "\n")


In [ ]:

y = np.array([[2,7,3],[8,3,5],[4,0,9]])
print("The original array:\n", y, "\n")

# Find the sum of elements by row
print("The sum of elements by row:\n",np.sum(y,axis=1), "\n")



In [ ]:

y = np.array([[2,7,3],[8,3,5],[4,0,9]])
print("The original array:\n", y, "\n")

# Find the sum of elements by column
print("The sum of elements by column:\n",np.sum(y,axis=0), "\n")


In [ ]:
y = np.array([[2,7,3],[8,3,5], [4,0,9]])
print("The original array:\n", y, "\n")
# Find the SD of all elements
print("The SD of all elements:\n", np.std(y), "\n")


In [ ]:
y = np.array([[2,7,3],[8,3,5], [4,0,9]])
print("The original array:\n", y, "\n")

# Find the SD of elements by row
print("The SD of elements by row:\n",np.std(y,axis=1), "\n")


In [ ]:
y = np.array([[2,7,3],[8,3,5], [4,0,9]])
print("The original array:\n", y, "\n")

# Find the SD of elements by column
print("The SD of elements by column:\n",np.std(y,axis=0), "\n")

In [ ]:
y = np.array([[2,7,3],[8,3,5],[4,0,9]])

# Find the min of all elements
print("The min of all elements:\n", np.min(y), "\n")

In [ ]:
y = np.array([[2,7,3],[8,3,5],[4,0,9]])

# Find the min of elements by row
print("The min of elements by row:\n",np.min(y,axis=1), "\n")

In [ ]:
y = np.array([[2,7,3],[8,3,5],[4,0,9]])

# Find the min of elements by column
print("The min of elements by row:\n",np.min(y,axis=0), "\n")

In [ ]:
y = np.array([[2,7,3],[8,3,5],[4,0,9]])

# Find the max of all elements
print("The max of all elements:\n", np.max(y), "\n")

In [ ]:
y = np.array([[2,7,3],[8,3,5],[4,0,9]])

# Find the max of elements by row
print("The max of elements by row:\n",np.max(y,axis=1), "\n")

In [ ]:
y = np.array([[2,7,3],[8,3,5],[4,0,9]])

# Find the max of elements by column
print("The max of elements by row:\n",np.max(y,axis=0), "\n")

In [ ]:
#where function x and y have same element
x=np.ones(10)
y=np.arange(10)

print(np.where(x == y), "\n")

In [ ]:
#where function x is greater than y 
x=np.ones(10)
y=np.arange(10)

print(np.where(x >= y), "\n")

In [ ]:
#where function 2x is greater than y with same index
x=np.ones(10)
y=np.arange(10)

print(np.where(2*x < y), "\n")

In [ ]:
#where function in second array elements gteater than 5
x=np.ones(10)
y=np.arange(10)

print(np.where(y > 5), "\n")

In [ ]:
x=np.random.randint(20,size=(10))

print(x)
np.where(x>5,x+5,x)