In [1]:
# create array using lists

import numpy as np
array_1D = np.array([1,2,3,4,5,6,7,8,9])
print(array_1D, "\n")

array_2D = np.array([[1,2,3,4],[5,6,7,8]])
print(array_2D)

[1 2 3 4 5 6 7 8 9] 

[[1 2 3 4]
 [5 6 7 8]]


In [2]:
# editing elements in array
# array[] = X

import numpy as np
array_1D = np.array([1,2,3,4,5,6,7,8])
print("original array:", array_1D, "\n")

# change first element from 1 to 88
array_1D[0] = 88
print("new array:", array_1D)


original array: [1 2 3 4 5 6 7 8] 

new array: [88  2  3  4  5  6  7  8]


In [3]:
# checking shape of array 
# arrayname.shape

import numpy as np

array_1 = np.array([1,2,3,4,5,6,7,8])
array_2 = np.array([[1,2,3,4],[5,6,7,8]])

# first array
print("array 1: \n", array_1)
print("shape of array 1: \n", array_1.shape, "\n")

# second array
print("array 2: \n", array_2)
print("shape of array 2: \n", array_2.shape, "\n")

array 1: 
 [1 2 3 4 5 6 7 8]
shape of array 1: 
 (8,) 

array 2: 
 [[1 2 3 4]
 [5 6 7 8]]
shape of array 2: 
 (2, 4) 



In [4]:
# creating arrays with NumPy functions
# np.zeros, np.ones

import numpy as np
zero = np.zeros((2,2));
print(zero, "\n")

one = np.ones((2,2))
print(one)

[[0. 0.]
 [0. 0.]] 

[[1. 1.]
 [1. 1.]]


In [5]:
# aranging
# np.arange

import numpy as np

# numpy.arange(stop)
print(np.arange(5))

# numpy.arange(start, stop)
print(np.arange(1, 10))

# numpy.arange(start, stop, step)
print(np.arange(1, 10, 2))


[0 1 2 3 4]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [6]:
# np.linspace
# np.linspace(start(inclusive), stop(inclusive), no. evenly spaced numbers)

import numpy as np

print(np.linspace(0, 10, 2))

print(np.linspace(0, 10, 5))

print(np.linspace(0, 10, )) # default 50 values

[ 0. 10.]
[ 0.   2.5  5.   7.5 10. ]
[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [7]:
# np.full
# np.full((0,0)array_value)

import numpy as np

full = np.full((2,2),8)
print(full)

[[8 8]
 [8 8]]


In [8]:
# np.eye

import numpy as np

# since identity matrix is a square matrix
# we just need one number to determine rows and columns

i_1 = np.eye(2)
print(i_1, "\n")

i_2 = np.eye(5)
print(i_2)

[[1. 0.]
 [0. 1.]] 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
# np.diag

import numpy as np

myarray = np.matrix([[1, 2, 3], [4, 5, 6], [9, 8, 7]])
print(myarray, "\n")

# returns first diagonal row
print(np.diag(myarray))

# returns second diagonal row
print(np.diag(myarray, 1))

# returns third diagonal row
print(np.diag(myarray, 2))

[[1 2 3]
 [4 5 6]
 [9 8 7]] 

[1 5 7]
[2 6]
[3]


In [10]:
# np.random.random

import numpy as np
random = np.random.random((3,3)) # size can be specified
print(random)

[[0.8110163  0.81584022 0.081531  ]
 [0.48896373 0.7650652  0.56155785]
 [0.00847468 0.01971074 0.01797374]]


In [11]:
# np.random.randint

import numpy as np

integer = np.random.randint(0,10, (3,3))

integer2 = np.random.randint(0,10, size=(3,3))
# you can omit "size=" and just write the brackets to indicate size

print(integer)
print()
print(integer2)

[[0 8 6]
 [1 4 5]
 [2 5 8]]

[[0 2 2]
 [2 4 9]
 [6 4 9]]


In [12]:
# array slicing 

import numpy as np 
myarray = np.array([[1, 2, 3], [4, 5, 6], [9, 8, 7]])
print(myarray, "\n")

# retrieving elements from rows
myarray = np.array([[1, 2, 3], [4, 5, 6], [9, 8, 7]])
print("row:", myarray[0,:])

# retrieving elements from columns
myarray = np.array([[1, 2, 3], [4, 5, 6], [9, 8, 7]])
print("column:", myarray[:,0], "\n")

# retrieving elements from rows and columns
myarray = np.array([[1, 2, 3], [4, 5, 6], [9, 8, 7]])
myarray_new = myarray[:2,:]

print("row and column: \n", myarray_new)
print()
print("shape: \n", myarray_new.shape)

[[1 2 3]
 [4 5 6]
 [9 8 7]] 

row: [1 2 3]
column: [1 4 9] 

row and column: 
 [[1 2 3]
 [4 5 6]]

shape: 
 (2, 3)


In [13]:
# reversing order of elements in arrays
# myarray[::-1]

import numpy as np
myarray = np.arange(8)

print("original array: \n", myarray, "\n")
print("reversed array: \n", myarray[::-1], "\n")

original array: 
 [0 1 2 3 4 5 6 7] 

reversed array: 
 [7 6 5 4 3 2 1 0] 



In [14]:
# page 13

In [15]:
# reshaping arrays
# .reshape(a,b), a=rows and b=columns

import numpy as np
myarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("original array: \n", myarray, "\n")

myarray_reshaped = myarray.reshape(1,9)

print("reshaped array: \n", myarray_reshaped, "\n")
print("reshaped array shape: \n", myarray_reshaped.shape)


# can automatically detect the column number using  -1

myarray1 = np.array([[0, 0, 0], [1, 1, 1], [2, 2, 2], [3, 3, 3]])

print("using reshape with automatic column number -1: \n")
print("original array: \n", myarray1, "\n")

print("reshaped array 1: \n", myarray1.reshape(1,-1), "\n")
print("reshaped array 2: \n", myarray1.reshape(3,-1), "\n")
print("reshaped array 3: \n", myarray1.reshape(4,-1), "\n")
print("reshaped array 4: \n", myarray1.reshape(6,-1), "\n")



original array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

reshaped array: 
 [[1 2 3 4 5 6 7 8 9]] 

reshaped array shape: 
 (1, 9)
using reshape with automatic column number -1: 

original array: 
 [[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]] 

reshaped array 1: 
 [[0 0 0 1 1 1 2 2 2 3 3 3]] 

reshaped array 2: 
 [[0 0 0 1]
 [1 1 2 2]
 [2 3 3 3]] 

reshaped array 3: 
 [[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]] 

reshaped array 4: 
 [[0 0]
 [0 1]
 [1 1]
 [2 2]
 [2 3]
 [3 3]] 



In [16]:
# condition
# NOT IN PDF

import numpy as np
x = np.random.randint(20, size=(10))
print(x)

# np.where(condition, display if true, display if false)
np.where(x > 5, x+5, x)

[ 3 13  2 18 11  5 12 16  7 14]


array([ 3, 18,  2, 23, 16,  5, 17, 21, 12, 19])

In [17]:
# math functions with NumPy 
# np.add, np.subtract, np.multiply, np.divide

x = np.array([[1,2],[4,8]])
y = np.ones((2,2))
print(x, "\n\n", y, "\n")

# method 1
print("Adding method 1:")
print(x+y)

# method 2
print("\nAdding method 2:")
print(np.add(x,y))

print("\nSubtracting:")
print(np.subtract(x,y))

print("\nMultiplying:")
print(np.multiply(x,y))

print("\nDividing:")
print(np.divide(x,y))


[[1 2]
 [4 8]] 

 [[1. 1.]
 [1. 1.]] 

Adding method 1:
[[2. 3.]
 [5. 9.]]

Adding method 2:
[[2. 3.]
 [5. 9.]]

Subtracting:
[[0. 1.]
 [3. 7.]]

Multiplying:
[[1. 2.]
 [4. 8.]]

Dividing:
[[1. 2.]
 [4. 8.]]


In [18]:
# square root
# np.sqrt(x + y)

import numpy as np
x = np.array([[1,2],[3,4]])
y = np.ones((2,2))
print(np.sqrt(x + y))

print()
print(np.sqrt(np.add(x,y)))


[[1.41421356 1.73205081]
 [2.         2.23606798]]

[[1.41421356 1.73205081]
 [2.         2.23606798]]


In [19]:
# matrix multiplication
# np.dot

import numpy as np

z = np.array([6,7])
x = np.array([[1,2],[3,4]])

print("array z shape:")
print(np.shape(z), "\n")

print("array x shape:")
print(np.shape(x), "\n")


# order matters in matrix multiplication
print(np.dot(z,x))

# [6,7] * [[1,2]
#          [3,4]]

# 6*1 + 7*3, 6*2 + 7*4


# we can see that z can be 2 by 1 or 1 by 2
print(np.dot(x,z))

# [[1,2] * [6,
#  [3,4]].  7]

# 1*6 + 2*7, 3*6 + 4*7

array z shape:
(2,) 

array x shape:
(2, 2) 

[27 40]
[20 46]


In [20]:
# sum 
# np.sum(array)

import numpy as np
x = np.array([[1,2],[3,4]])
print("table: \n", x, "\n")
print("sum:", np.sum(x), "\n")


# sum of each column
# we need to specify axis = 0

import numpy as np
y = np.array([[1,2],[3,4]])
print("axis=0, row")
print(np.sum(y, axis=0))
print()

# sum of each row
# we need to specify axis = 1

import numpy as np
y = np.array([[1,2],[3,4]])
print("axis=1, column")
print(np.sum(y, axis=1))

table: 
 [[1 2]
 [3 4]] 

sum: 10 

axis=0, row
[4 6]

axis=1, column
[3 7]


In [21]:
# combining 2 arrays
# concatenate(array1, array2)

import numpy as np
x = np.arange(10).reshape(5,-1)
y = np.arange(10,20).reshape(5,-1 )
print(x,"\n\n", y)

# stack horizontally
# | + | = ||
import numpy as np
print("\nfirst array is: \n", x)
print("\nsecond array is: \n", y, "\n")
print("combined array is: \n", np.concatenate([x,y], axis=1), "\n")

# stack vertically
# –– + –– = –– 
#           ––
print("\nfirst array is: \n", x)
print("\nsecond array is: \n", y, "\n")
print("combined array is: \n", np.concatenate([x,y], axis=0), "\n")





[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 

 [[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]

first array is: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

second array is: 
 [[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]] 

combined array is: 
 [[ 0  1 10 11]
 [ 2  3 12 13]
 [ 4  5 14 15]
 [ 6  7 16 17]
 [ 8  9 18 19]] 


first array is: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

second array is: 
 [[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]] 

combined array is: 
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]] 



In [22]:
# adding elements to arrays
# np. append

import numpy as np
x = np.array([1,2,3,4])
print(x)
x = np.append(x, 69)
print(x, "\n")

# adding multiple elements to 1D arrays
import numpy as np
x = np.array([1,2,3,4])
print(x)
x = np.append(x,[12,13])
print(x, "\n")

# adding extra rows to 2D arrays
y = np.array([[1,2],[3,4]])
y = np.append(y,[[11,22]], axis=0)
print(y, "\n\n")

# adding extra columns to 2D arrays
z = np.array([[1,2],[3,4]])
z = np.append(z,[[33],[77]], axis=1)
print(z)

[1 2 3 4]
[ 1  2  3  4 69] 

[1 2 3 4]
[ 1  2  3  4 12 13] 

[[ 1  2]
 [ 3  4]
 [11 22]] 


[[ 1  2 33]
 [ 3  4 77]]


In [23]:
# inserting elements into arrays
# np.insert(ndarray, index, elements, axis)
# you get to insert at any specified spot compared to append

# inserting elements to a row in 1D arrays
import numpy as np
x = np.array([1,2,3,4])
print("original array:", x)
x = np.insert(x, 2,[11,12,13])
print("\nupdated array, inserted row element:", x)

# inserting elements to a row in 2D arrays
import numpy as npp
y = np.array([[1,2],[3,4]])
print("\noriginal array: \n", y)

y = np.insert(y,1,[11,12], axis=0)
print("\nupdated array, inserted rows: \n", y)

# insert elements to a column in 2D arrays 
import numpy as np
y = np.array([[1,2],[3,4]])
print("\noriginal array: \n", y)

y = np.insert(y, 2, 55, axis=1)
print("\nupdated array, inserted column element: \n", y)

original array: [1 2 3 4]

updated array, inserted row element: [ 1  2 11 12 13  3  4]

original array: 
 [[1 2]
 [3 4]]

updated array, inserted rows: 
 [[ 1  2]
 [11 12]
 [ 3  4]]

original array: 
 [[1 2]
 [3 4]]

updated array, inserted column element: 
 [[ 1  2 55]
 [ 3  4 55]]


In [24]:
# deleting elements from arrays
# np.delete(ndarray, elements, axis)

# deleting elements from 1D arrays
import numpy as np
x = np.array([1,2,3,4])
print("original: ",x)
x = np.delete(x,[0,2])
print("deleted: ",x)

# deleting elements from 2D arrays
import numpy as np
y = np.array([[1,2],[3,4]])
print("\noriginal array:\n", y)

y = np.delete(y, 0, axis=1)
print("\nupdated array:\n", y)

z = np.array([[1,2],[3,4]])
print("\noriginal array:\n", y)

z = np.delete(z, 0, axis=0)
print("\nupdated array:\n", z)

original:  [1 2 3 4]
deleted:  [2 4]

original array:
 [[1 2]
 [3 4]]

updated array:
 [[2]
 [4]]

original array:
 [[2]
 [4]]

updated array:
 [[3 4]]


In [25]:
# sorting elements in arrays
# np.sort
# the axis is a bit tricky in the rows and columns part so look out for that

import numpy as np
x = np.array([3,1,2,4])
print(x, "\n")

# when used as a function, the original array stays the same because new variable
sort = np.sort(x)
print(sort)

# when used as a method, the original array changes
x.sort()
print(x)


# sorting by rows and columns
import numpy as np
y = np.array([[2,7,3],[8,3,5],[4,0,9]])
print("\n\noriginal array: \n", y)

# sorting elements in rows
y = np.sort(y, axis=1)
print("\nsorted rows: \n", y)

# sorting elements in columns
y = np.sort(y, axis=0)
print("\nsorted columns: \n", y)

[3 1 2 4] 

[1 2 3 4]
[1 2 3 4]


original array: 
 [[2 7 3]
 [8 3 5]
 [4 0 9]]

sorted rows: 
 [[2 3 7]
 [3 5 8]
 [0 4 9]]

sorted columns: 
 [[0 3 7]
 [2 4 8]
 [3 5 9]]


In [26]:
# math with numpy II
# using mean, standard deviation and minimum/ maximum values
# watch out for the axis parts

import numpy as np
y = np.array([[2,7,3],[8,3,5],[4,0,9]])

# finding the mean of all the elements
print("the mean of all elements:\n", y.mean())

# find the mean of elements in the rows
print("the mean of elements in rows:\n", y.mean(axis=1))

# find the mean of elements in the columns
print("the mean of elements in columns:\n", y.mean(axis=0))

the mean of all elements:
 4.555555555555555
the mean of elements in rows:
 [4.         5.33333333 4.33333333]
the mean of elements in columns:
 [4.66666667 3.33333333 5.66666667]


In [27]:
# standard deviation
# np.std

import numpy as np
y = np.array([[2,7,3],[8,3,5],[4,0,9]])

# find the SD of all elements
print("the SD of all elements: \n", np.std(y), "\n")

# find the SD of elements by row
print("the SD of elements by row: \n", np.std(y,axis=1), "\n")

# find the SD of elements by column
print("the SD of elements by column: \n", np.std(y,axis=0), "\n")


the SD of all elements: 
 2.7932900199947857 

the SD of elements by row: 
 [2.1602469  2.05480467 3.68178701] 

the SD of elements by column: 
 [2.49443826 2.86744176 2.49443826] 

